[package]
name = "is-admin"
version = "0.1.2"
edition = "2021"
resolver = "2"
license = "MIT"
description = "is-admin"
repository = "https://github.com/ahaoboy/is-admin"
homepage = "https://github.com/ahaoboy/is-admin"
authors = ["ahaoboy"]

[target.'cfg(unix)'.dependencies]
libc = "^0.2"
